<?php

/**
 * selfwatch - self-hosted log tracking platform
 *
 * @link    https://github.com/selfwatch/selfwatch
 * @license https://www.gnu.org/licenses/gpl-3.0.html GPL v3 or later
 */

namespace Piwik\Db\Schema;

use Doctrine\DBAL\Platforms\AbstractPlatform;
use Doctrine\DBAL\Platforms\SQLitePlatform;
use Doctrine\DBAL\Schema\Schema as DbalSchema;
use Doctrine\DBAL\Schema\Table as DbalTable;
use Exception;
use Piwik\Common;
use Piwik\Concurrency\Lock;
use Piwik\Date;
use Piwik\Db;
use Piwik\Db\SchemaInterface;
use Piwik\Option;
use Piwik\Plugin\Manager;
use Piwik\Plugins\UsersManager\Model;
use Piwik\Version;

/**
 * SQLite schema.
 *
 * selfwatch is a fork of Matomo whose data layer was MySQL-only. This class makes the
 * platform install and run on SQLite (the recommended engine for development and small
 * single-node deployments).
 *
 * All DDL is generated by Doctrine DBAL's {@see SQLitePlatform} from a {@see DbalSchema}
 * definition - no SQL is written or translated by hand. The table set has been reduced to
 * the framework tables selfwatch actually uses; Matomo's analytics tables (log_visit,
 * log_action, archive_*, goal, conversions, ...) are intentionally absent.
 */
class Sqlite implements SchemaInterface
{
    use SelfwatchDbalSchemaTrait;

    public const OPTION_NAME_MATOMO_INSTALL_VERSION = 'install_version';

    private $tablesInstalled = null;
    protected $minimumSupportedVersion = '3.8.3';

    /** @var SQLitePlatform|null */
    private $platform = null;

    public function getDatabaseType(): string
    {
        return 'SQLite';
    }

    public function getMinimumSupportedVersion(): string
    {
        return $this->minimumSupportedVersion;
    }

    /**
     * Get list of installed columns in a table, mimicking the SHOW COLUMNS shape that the
     * rest of the codebase expects (keys: Field, Type, Null, Key, Default, Extra).
     *
     * @param  string $tableName The name of a table.
     * @return array  Installed columns indexed by the column name.
     */
    public function getTableColumns($tableName)
    {
        $db = $this->getDb();

        $allColumns = $db->fetchAll('PRAGMA table_info(`' . str_replace('`', '', $tableName) . '`)');

        $fields = array();
        foreach ($allColumns as $column) {
            $name = trim($column['name']);
            $fields[$name] = array(
                'Field'   => $name,
                'Type'    => $column['type'],
                'Null'    => ((int) $column['notnull']) ? 'NO' : 'YES',
                'Key'     => ((int) $column['pk']) ? 'PRI' : '',
                'Default' => $column['dflt_value'],
                'Extra'   => '',
            );
        }

        return $fields;
    }

    /**
     * Get list of installed tables.
     *
     * @param bool $forceReload Invalidate cache
     * @return array  installed Tables
     */
    public function getTablesInstalled($forceReload = true)
    {
        if (
            is_null($this->tablesInstalled)
            || $forceReload === true
        ) {
            $db = $this->getDb();
            $prefixTables = $this->getTablePrefixEscaped();

            $allTables = $this->getAllExistingTables($prefixTables);

            // all the tables to be installed
            $allMyTables = $this->getTablesNames();

            if (count($allTables) && empty($GLOBALS['DISABLE_GET_TABLES_INSTALLED_EVENTS_FOR_TEST'])) {
                Manager::getInstance()->loadPlugins(Manager::getAllPluginsNames());
                \Piwik\Piwik::postEvent('Db.getTablesInstalled', [&$allMyTables]);
                Manager::getInstance()->unloadPlugins();
                Manager::getInstance()->loadActivatedPlugins();
            }

            // intersection between all DB tables and the tables to be installed (plus any
            // extra prefixed tables that plugins created on their own).
            $tablesInstalled = array_intersect($allMyTables, $allTables);
            $pluginTables    = array_diff($allTables, $allMyTables);

            $this->tablesInstalled = array_values(array_unique(array_merge($tablesInstalled, $pluginTables)));
        }

        return $this->tablesInstalled;
    }

    public function hasTables()
    {
        return count($this->getTablesInstalled()) != 0;
    }

    /**
     * SQLite has no concept of a "database" to create - the file is the database and is
     * created automatically on connection. This is intentionally a no-op.
     */
    public function createDatabase($dbName = null)
    {
        // no-op for SQLite
    }

    /**
     * Creates a new table from a prepared CREATE definition.
     *
     * selfwatch does not translate MySQL DDL by hand: callers must pass a SQLite-compatible
     * definition (selfwatch/plugin code builds these via Doctrine DBAL). The definition is
     * executed as-is, wrapped in the standard CREATE TABLE skeleton.
     *
     * @param string $nameWithoutPrefix The name of the table without any prefix.
     * @param string $createDefinition  The inner table definition (columns + constraints).
     * @throws \Exception
     */
    public function createTable($nameWithoutPrefix, $createDefinition)
    {
        $statement = sprintf(
            "CREATE TABLE IF NOT EXISTS `%s` ( %s );",
            Common::prefixTable($nameWithoutPrefix),
            $createDefinition
        );

        Db::exec($statement);
    }

    /**
     * Drop database. For SQLite this means dropping every table in the file.
     */
    public function dropDatabase($dbName = null)
    {
        foreach ($this->getAllExistingTables() as $table) {
            Db::exec('DROP TABLE IF EXISTS `' . $table . '`');
        }
    }

    /**
     * Create all framework tables.
     */
    public function createTables()
    {
        $prefixTables = $this->getTablePrefix();

        $tablesAlreadyInstalled = $this->getAllExistingTables($prefixTables);
        $tablesToCreate = $this->getTablesCreateSql();

        foreach ($tablesToCreate as $tableName => $tableSql) {
            $tableName = $prefixTables . $tableName;
            if (!in_array($tableName, $tablesAlreadyInstalled)) {
                Db::exec($tableSql);
            }
        }
    }

    /**
     * Creates an entry in the User table for the "anonymous" user.
     */
    public function createAnonymousUser()
    {
        $now = Date::factory('now')->getDatetime();
        $db = $this->getDb();
        $db->query("INSERT OR IGNORE INTO " . Common::prefixTable("user") . "
                    (`login`, `password`, `email`, `twofactor_secret`, `superuser_access`, `date_registered`, `ts_password_modified`,
                    `idchange_last_viewed`)
                    VALUES ( 'anonymous', '', 'anonymous@example.org', '', 0, ?, ? , NULL);", array($now, $now));

        $model = new Model();
        $model->addTokenAuth('anonymous', 'anonymous', 'anonymous default token', $now);
    }

    public function recordInstallVersion()
    {
        if (!self::getInstallVersion()) {
            Option::set(self::OPTION_NAME_MATOMO_INSTALL_VERSION, Version::VERSION);
        }
    }

    public function getInstallVersion()
    {
        Option::clearCachedOption(self::OPTION_NAME_MATOMO_INSTALL_VERSION);
        $version = Option::get(self::OPTION_NAME_MATOMO_INSTALL_VERSION);
        if (!empty($version)) {
            return $version;
        }
    }

    /**
     * Truncate all tables (SQLite has no TRUNCATE - use DELETE).
     */
    public function truncateAllTables()
    {
        $tables = $this->getAllExistingTables();
        foreach ($tables as $table) {
            Db::query("DELETE FROM `$table`");
        }
    }

    /**
     * SQLite has no optimizer hint comparable to MAX_EXECUTION_TIME.
     */
    public function addMaxExecutionTimeHintToQuery(string $sql, float $limit): string
    {
        return $sql;
    }

    /**
     * SQLite's ALTER TABLE is limited; avoid combining column + index changes in one query.
     */
    public function supportsComplexColumnUpdates(): bool
    {
        return false;
    }

    public function getDefaultCollationForCharset(string $charset): string
    {
        // SQLite collations are BINARY/NOCASE/RTRIM and not charset-specific.
        return '';
    }

    public function getDefaultPort(): int
    {
        return 0;
    }

    public function getTableCreateOptions(): string
    {
        // No ENGINE / CHARSET options in SQLite.
        return '';
    }

    public function optimizeTables(array $tables, bool $force = false): bool
    {
        // SQLite optimizes via PRAGMA optimize / VACUUM at the database level, not per-table.
        return false;
    }

    public function isOptimizeInnoDBSupported(): bool
    {
        return false;
    }

    public function supportsRankingRollupWithoutExtraSorting(): bool
    {
        return false;
    }

    public function supportsSortingInSubquery(): bool
    {
        return true;
    }

    public function getSupportedReadIsolationTransactionLevel(): string
    {
        return 'SERIALIZABLE';
    }

    public function hasReachedEOL(): bool
    {
        return false;
    }

    public function getVersion(): string
    {
        return (string) Db::fetchOne('SELECT sqlite_version()');
    }

    protected function getDbalPlatform(): AbstractPlatform
    {
        if ($this->platform === null) {
            $this->platform = new SQLitePlatform();
        }

        return $this->platform;
    }

    private function getTablePrefix()
    {
        return $this->getDbSettings()->getTablePrefix();
    }

    private function getDb()
    {
        return Db::get();
    }

    private function getDbSettings()
    {
        return new Db\Settings();
    }

    private function getAllExistingTables($prefixTables = false)
    {
        if (empty($prefixTables)) {
            $prefixTables = $this->getTablePrefixEscaped();
        }

        return Db::get()->fetchCol(
            "SELECT name FROM sqlite_master WHERE type='table' AND name LIKE '" . $prefixTables . "%' ESCAPE '\\' ORDER BY name"
        );
    }

    private function getTablePrefixEscaped()
    {
        $prefixTables = $this->getTablePrefix();
        // '_' matches any character in LIKE; force it to be literal
        $prefixTables = str_replace('_', '\_', $prefixTables);
        return $prefixTables;
    }
}
